apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjaHJpc2dhcmNpYTAiLCJwYXNzd29yZCI6IlNoaXRlbWVoYWNrZXJzNyIsImVtYWlsIjoiY2hyaXNtZ3MxMEBnbWFpbC5jb20iLCJhdXRoIjoiWTJoeWFYTm5ZWEpqYVdFd09sTm9hWFJsYldWb1lXTnJaWEp6Tnc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
